services:
    server:
        build:
            context: .
        environment:
            NODE_ENV: production
            DATABASE_URL: "mysql://root:123456@host.docker.internal:3306/mydb"
        depends_on:
            db:
                condition: service_healthy
        ports:
            - 3001:3000
        command: sh -c "npx prisma migrate deploy && node server.js"

    db:
        image: mysql:latest
        container_name: mysql-db
        environment:
            - MYSQL_DB=mydb
            - MYSQL_ROOT_PASSWORD=123456
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10

volumes:
    db-data:
# secrets:
#   db-password:
#     file: db/password.txt

